### ISSUE TITLE
Movimento da câmera

### ISSUE THREAD

**Issue by mrplcardoso** [Bento-Quirino/DJD2D3D#6]
Câmera deve pular de cenário em cenário, um por vez, e quando chegar nos limites (primeiro ou ultimo(, deve dar a volta na lista de cenários.

Para mover a câmera basta apenas posiciona-la na mesma posição do cenários.
Cada cenario precisa corresponder a um objeto vazio que contem o spawn dos inimigos, a imagem do cenário e outros elementos específicos do cenário.
O botões devem estar num canvas que faz parte do mundo do jogo (world space).

**Comment by mrplcardoso** [comment]
14/10

**Comment by DevAry-Inrry** [comment]
Esse foi o código usado, mas fica sem contexto fora do projeot, então estou mandando o projeto junto:
[RevivalJam.zip](https://github.com/user-attachments/files/17403319/RevivalJam.zip)



using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraManager : MonoBehaviour
{
    [SerializeField] private Transform cameraTF;

    [SerializeField] private Vector3[] positions;


    public void SetCameraPosFront()
    {
        cameraTF.position = positions[0];
    }
    public void SetCameraPosRight()
    {
        cameraTF.position = positions[1];
    }
    public void SetCameraPosBack()
    {
        cameraTF.position = positions[2];
    }
    public void SetCameraPosLeft()
    {
        cameraTF.position = positions[3];
    }
}
