### ISSUE TITLE
Movimento do inimigos

### ISSUE THREAD

**Issue by mrplcardoso** [Bento-Quirino/DJD2D3D#7]
Os inimigos  não deslocam sua posição. A ilusão de movimento deve ser feita manipulando o tamanho dos objetos.
Garantir que a ancoragem da Sprite está no centro do objeto.

**Comment by mrplcardoso** [comment]
9/10

**Comment by Carrtz** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyMovement : MonoBehaviour
{
    private float Speed = 5f;
    private Vector3 inicialPosition;

    public float distance => Vector3.Distance(inicialPosition, transform.localScale);
    public readonly float MaxDistance = 10;

    void Start()
    {
        inicialPosition = transform.localScale;
    }

    // Update is called once per frame
    void Update()
    {
        if (distance >= MaxDistance)
          return;
        transform.localScale += new Vector3(1, 1) * Speed * Time.deltaTime;
       
    }

}

**Comment by mrplcardoso** [comment]
@Carrtz 
if (newScale.y > MaxHeight)
    {
        newScale.y = MaxHeight; 
      
    }

    // Verifica se a nova scale ultrapassa a largura máxima
    if (newScale.x > MaxWidth)
    {
        newScale.x = MaxWidth; 
    }
    
    isso pode ser feito com Vector2.Clamp()

**Comment by mrplcardoso** [comment]
@Carrtz 
if (distance >= MaxDistance && Time.time - startTime >= 5f)
    {
        if (OnDistanceReached != null)
        {
            OnDistanceReached();
        }
        // Desabilita o aumento do inimigo na tela apos 5 segundos de atingir a altura máxima (revisar tempo balanceado depois)
        enabled = false;
    }
transforma essa parte em uma Coroutine/IEnumerator
